// This code was generated by a tool.
// Processing tool available at https://github.com/mezoni/binary_generator

import "package:binary_interop/binary_interop.dart";

class Libc {
  String _header = '''
int printf(const char *format, ...);
int sprintf(char *str, const char *format, ...);
size_t strlen(const char *s);''';

  DynamicLibrary _library;

  /**
   *
   */
  Libc(DynamicLibrary library) {
    if (library == null) {
      throw new ArgumentError.notNull("library");
    }

    library.declare(_header);
    _library = library;
  }

  /**
   * int printf(char* format, ...)
   */
  int printf(format, [List params]) {
    var arguments = [format];
    if (params != null) {
      arguments.addAll(params);
    }

    return _library.invoke("printf", arguments);
  }

  /**
   * int sprintf(char* str, char* format, ...)
   */
  int sprintf(str, format, [List params]) {
    var arguments = [str, format];
    if (params != null) {
      arguments.addAll(params);
    }

    return _library.invoke("sprintf", arguments);
  }

  /**
   * size_t strlen(char* s)
   */
  int strlen(s) {
    return _library.invoke("strlen", [s]);
  }

}

